    #############################################################################
    #############################################################################
    ######### Managed by Terraform, not safe to change ##########################
    #############################################################################
    #############################################################################
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  values:
    domainFilters:
      - jeqo-tf.local

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/jeqo-tf-external-dns
